<Project Sdk="Aspire.AppHost.Sdk/13.4.6">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>077dd017-ef6a-45aa-8d02-7b9a98930487</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NikuUniversity.ApiService\NikuUniversity.ApiService.csproj" />
    <ProjectReference Include="..\NikuUniversity.App\NikuUniversity.App.csproj">
      <SetTargetFramework>TargetFramework=net10.0</SetTargetFramework>
    </ProjectReference>
    <ProjectReference Include="..\NikuUniversity.Web\NikuUniversity.Web.csproj" />
    <ProjectReference Include="..\NikuUniversity.Worker\NikuUniversity.Worker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
  </ItemGroup>

</Project>
